### PR TITLE
Added basic automated installer

### LINKED ISSUE #70: Basic auto installer.
Basic Auto installer to run without confirmation.

- [x] Removes MS store app.

- [x] Installs recommended version

### PR DESCRIPTION
**Pull request by Nuzair46**
@amd64fox , Please review.
closes #70 
This installer and ps command will be used on BlockTheSpot repo as to make have a clean installation of the BlockTheSpot only.

### CODE REVIEW

**Comment by amd64fox** [comment]
@Nuzair46 
There are no parameters for the functions of blocking updates, blocking podcasts and clearing the cache, in which case questions will pop up confirming these parameters, it turns out that the installer is not quite automatic, do you really want it?

If you do not need these features in your installer, you must specify in the options to disable them, then the installation will not show confirmations with them.

for example, the `-podcasts_on` - don't remove podcasts from homepage
`-block_update_off` - don't block Spotify automatic updates
`-cache_off` - don't enable cache clearing

**Comment by Nuzair46** [comment]
ok. I thought the commands are more based on the truthy values.
will make the required changes.

**Comment by Nuzair46** [comment]
@amd64fox made the required changes. please review

**Comment by amd64fox** [comment]
@Nuzair46 Automatic cache cleaning is enabled, by default for 7 days, right?

**Comment by Nuzair46** [comment]
@amd64fox , I've passed the param `cache_off`. This is the default right?
The main purpose of this change is that, we need to have just the basic auto installation of BlockTheSpot where only the MS store app will be uninstalled and recommended Spotify version will be installed. Any other changes should not happen.
Please make the required change and let me know if the other commands are not the default and failing the requirement I mentioned.

**Comment by amd64fox** [comment]
@Nuzair46 
> I've passed the param `cache_off`. This is the default right?

no you typed `-cache_on` - this includes automatic cache installation.

Yes, I'll fix it now.
Also, if you do not need [experimental features](https://github.com/amd64fox/SpotX/discussions/50), I can add a key to disable them, do you need ?

**Comment by Nuzair46** [comment]
@amd64fox yea add it. that'd be great

**Comment by amd64fox** [comment]
@Nuzair46 
I did it, the only thing now with the complete disabling of experimental functions, [this](https://github.com/mrpond/BlockTheSpot/issues/385) and [this](https://github.com/mrpond/BlockTheSpot/issues/371) problem may appear, I will finalize a smarter disabling of experimental functions a little later.

**Review by amd64fox — APPROVED** [review]

**Pull request merged**
