### PR TITLE
Added a function to assign language strings.

### PR DESCRIPTION
**Pull request by dembeck**
Added a function to assign language strings to improve the organization of the script and increase future flexibility.

This should not cause any issues or require any other changes to the script.

Removed lines 69 to 201
Added lines 69 to 256

### CODE REVIEW

**Comment by amd64fox** [comment]
Wow, thanks a lot for a more elegant look than mine.

Can you also add an a new incoming parameter at the beginning of the code that will run a specific language type regardless of what language was defined on the system, if required.


For example, if you run this command directly from the powershell:

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $(iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1') } -ru"
```
then the forced installation in Russian begins.

**Comment by dembeck** [comment]
# New Parameter

**-Language | -l**

I added an optional language parameter ```Language``` with an alias of ```l```. Users can use one of the following to select a language:

**Using the parameter -Language**
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1') } -Language ru"
```

**Using the parameter alias -l (lowercase 'L')**
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1') } -l ru"
```

# New Function

**Format-LanguageCode**

This function that takes whatever the user inputs and tries to match it to a language supported by the script, currently en and ru. Then outputs a normalized two-letter code. As long as the user inputs something that starts with the letters 'en', 'py', or 'ru' it will find a match.

If the input cannot be matched to a supported language for any reason (null or unsupported language) it, then:
  1. Tries to match the system language.
  2. If that is unsuccessful it defaults to English.

**Examples of the current outputs:**

```powershell
Input      Output
------     ------
en         en
en-US      en
en-UK      en
English    en
ru         ru
ru-RU      ru
Russian    ru
русский    ru
es         en
Mandarin   en
```

# Renamed Function

The function ```Set-ScriptLanguage``` was renamed to ```Set-ScriptLanguageStrings``` as it now only handles assigning strings in the appropriate language.

# Other

  - Added help messages to all parameters for better readability of the script.
  - Three other lines were also added or modified. Shown below.

**Set the normalized language code.**

```powershell
$langCode = Format-LanguageCode -LanguageCode $Language
```

**Set the language strings for the script.**

```powershell
$lang = Set-ScriptLanguageStrings -LanguageCode $langCode
```


**Set the value of the ```ru``` variable for other parts of the script.**

```powershell
if ($langCode -eq 'ru') { $ru = $true }
```

**Comment by amd64fox** [comment]
Oh .. exactly what is needed, thank you

Another question, I see in the parameters now there is "HelpMessage" does it throw its text into the console?

**Comment by dembeck** [comment]
The ```HelpMessage``` parameter argument is only shown to the user for mandatory parameters when a value is not supplied. If a parameter is not mandatory it is ignored. As none of the parameters are mandatory in this script, the user will never see them unless they look at the code.

I added the help messages more for code documentation purposes, but I can remove them if you want.

**Comment by amd64fox** [comment]
ok, all is well then

Thanks again for your valuable input.

**Comment by dembeck** [comment]
Here is a quick example of when the ```HelpMessage``` is seen.

**Test Function**
```powershell
function Test-HelpMessage
{
    param (
        [Parameter(
            Mandatory = $true,
            HelpMessage = 'This help message tells you about the mandatory parameter.'
        )]
        [string]$MandatoryParam,

        [Parameter(
            HelpMessage = 'This help message is never seen.'
        )]
        [string]$NotMandatoryParam
    )

    $MandatoryParam

    $NotMandatoryParam
}
```

**Console**
The user is shown the ```HelpMessage``` after not supplying a value, and then entering ```!?```
```powershell
PS C:\> Test-HelpMessage

cmdlet Test-HelpMessage at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
MandatoryParam: !?
This help message tells you about the mandatory parameter.
MandatoryParam: 
```

**Get-Help**
```Get-Help``` does not see the ```HelpMessage```
```powershell
PS C:\> Get-Help Test-HelpMessage

NAME
    Test-HelpMessage
    
SYNTAX
    Test-HelpMessage [-MandatoryParam] <string> [-NotMandatoryParam] <string> [<CommonParameters>]
    

ALIASES
    None
    

REMARKS
    None
```

**Comment by amd64fox** [comment]
Thanks for the explanation, didn't know it worked like that.

**Comment by amd64fox** [comment]
@dembeck 
just now I saw if you run Install.ps1 without parameters, for example like this:
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content | iex
```
then it throws an error:
```txt
iex : Cannot add attribute because that would make the 'Language' variable with a value invalid.
string:1 character:172
```

Upd. fixed

**Pull request merged**
