### PR TITLE
added validations / auto-complete for lyrics_stat param

### PR DESCRIPTION
**Pull request by sharunkumar**
Validation list taken from: https://github.com/amd64fox/SpotX/discussions/50#discussioncomment-4096066

Helps when invoking install.ps1 manually:

Recording 2023-06-02 193539

### CODE REVIEW

**Comment by amd64fox** [comment]
add the last 2 themes `relish` and `turquoise`

**Comment by sharunkumar** [comment]
> add the last 2 themes `relish` and `turquoise`

done 👍🏻

**Comment by amd64fox** [comment]
I had to restore the code to its original state because in some cases running the script was producing an error

You can reproduce the error by looking at this [issue](https://github.com/amd64fox/SpotX/issues/429).

**Comment by sharunkumar** [comment]
Strange, seems like there's an issue when invoke-expression tries to execute the code without the default parameter, but when manually invoking it from the command line, it works. I think its got something to do with invoke-expression handling the parameters. I might have to look more into it. but I could suggest another change where autocomplete can be added without the validations though

https://github.com/PowerShell/PowerShell/issues/8778

**Pull request merged**
