### PR TITLE
added ArgumentCompleter for lyrics_stat param

### PR DESCRIPTION
**Pull request by sharunkumar**
This is an alternative to #428, without the issue in #429 

I have tested it by invoking `Install_Old_theme.bat` in my [test branch](https://github.com/sharunkumar/SpotX/tree/test) after replacing the urls to make sure the powershell script is running

### CODE REVIEW

**Comment by amd64fox** [comment]
Yes, it does seem like a problem with `Invoke-Expression`

Tell me how to make it work like shown in your gif from #428 , do I need to install an additional module or use a special terminal?

**Comment by sharunkumar** [comment]
> install an additional module or use a special terminal

it should work out of the box on Powershell, after typing `.\Install.ps1 -lyrics_stat ` then press tab to auto complete

**Comment by sharunkumar** [comment]
Oh also if you were asking about the prompt it's oh my posh: https://ohmyposh.dev/

**Comment by amd64fox** [comment]
Oh damn, I didn't know Tab was used for that, thanks.

**Pull request merged**
