### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by peter9811**
Spanish translation

### CODE REVIEW

**Comment by amd64fox** [comment]
i added a line
`Autor de la traducción: @peter9811`
correct translation?
i used google translate

**Comment by peter9811** [comment]
> i added a line `Autor de la traducción: @peter9811` correct translation? i used google translate

Yes, correct translation. Thanks

**Comment by amd64fox** [comment]
Thanks for your work
merged

**Comment by peter9811** [comment]
And sorry about the order of 'es', I tried to do it alphabetically, I don't know

**Comment by amd64fox** [comment]
Everything is fine

**Pull request merged**
