### PR TITLE
Use PS7 if available for translation

### PR DESCRIPTION
**Pull request by CDzungx**
Check if [Powershell 7 ](https://github.com/PowerShell/PowerShell)available and use it for translation to work, else still old command (No translation).
Need update for other .bat installer.

### CODE REVIEW

**Comment by amd64fox** [comment]
what advantage does it give?

Or does it fix some bug?
if so, how can i reproduce it?

**Comment by CDzungx** [comment]
> what advantage does it give?
> 
> Or does it fix some bug? if so, how can i reproduce it?

I have written it already, When you use old PS, there is no translation 🤔 The translation will work using PS7.

**Comment by CDzungx** [comment]
image
Left: Using PS7 (new script) || Right: Old script: No translation.

**Comment by amd64fox** [comment]
That is unnecessary.

While running the spotx installation, the script looks at the locale of your PowerShell terminal, if it finds a supported language it will be changed, if it doesn't find any supported languages it will default to English.

So just change the locale of your PowerShell 5 terminal or add an input parameter to the spotx installer like `-l it` which will force the language you need.

**Pull request closed without merging**
